### ISSUE TITLE
the size has no effect on Heading field.

### ISSUE THREAD

**Issue by issour** [codenco-dev/nova-grid-system#2]
Many thx

**Comment by thomasdominic** [comment]
Hi @issour 
Can you tell me what are Heading Fields for you ? 
With an example ?

Thanks you

**Comment by issour** [comment]
Hi @thomasdominic 
it's like : `Heading::make('<p class="text-danger">(*) all fields are required.</p>')`
Many thx

**Comment by thomasdominic** [comment]
In your opinion, what will it do ?
A new line ? IMO, it must be "break the flow"
_It is used to display a banner across your forms and can function as a separator for long lists of fields_

**Comment by issour** [comment]
Hi, Heading is always w-full. But for more flexibility I think can behave like any other field.
Thanks you !

**Comment by Ragash** [comment]
+1 that's very much needed, it will help operating with third party fields without breaking it all (ex. translation fields)

**Comment by thomasdominic** [comment]
@Ragash @issour 
Give me your feedback after trying this.

Thanks

**Comment by Ragash** [comment]
That's perfect! thank you very much!
