### ISSUE TITLE
Use specific grid class on all fields

### ISSUE THREAD

**Issue by bernhardh** [codenco-dev/nova-grid-system#6]
I want to apply `->size("w-1/3")` to all fields per default and only change it on the field itself if needed. Is there a way, to apply it to all fields, without adding it to every single one?

**Comment by thomasdominic** [comment]
Hi, do you want apply it on all files (edit, show ?) and for all resources ? Or do you want choose default value for each resource ?

**Comment by bernhardh** [comment]
Good question. I think it would be enought, if I could pick a default value for all resources, but it should be possible to distinguish between edit and show. So for example, all edit views should get `w-1/2` and all detail pages should get`w-1/3` by default.

**Comment by thomasdominic** [comment]
@bernhardh Can you look that ?

https://github.com/codenco-dev/nova-grid-system/blob/1.0.0/README.md#play-with-default-values

your feedback are welcome

**Comment by bernhardh** [comment]
Thanks! Thats great and what I was looking for.
