### ISSUE TITLE
Not working properly in action fields

### ISSUE THREAD

**Issue by romaldyminaya** [codenco-dev/nova-grid-system#8]
Hi,

Firstly thanks for this package.

Second, when using it on forms is working good as expected but when using it on action fields, is not.

Here the portion of the code example and image.

![image](https://user-images.githubusercontent.com/2809147/90199567-2b0e8100-dda3-11ea-86eb-c6d52f71e8e2.png)

![image](https://user-images.githubusercontent.com/2809147/90199481-eaaf0300-dda2-11ea-8c80-6427c73d09e5.png)

Is there any way possible for you to check this ?

**Comment by thomasdominic** [comment]
Hi,

Please, for faster resolution, can you give me a whole class ?

**Comment by thomasdominic** [comment]
Done.

Thanks for your feedback please.
